### ISSUE TITLE
Size Mismatch

### ISSUE THREAD

**Issue by Miora2020** [imoken1122/ID-CVAE#2]
Hello, I am new in coding but I do search in IDS by using CVAE mtehod. I found your code then I wanna try to condition the encoder network by a class label to check the result.
When I run the code by changing the model into condition encoder-decoder, I always got a size mismatch error, Could you advice me how could I modify it with both condition encoder and decoder.

**Comment by NaturalShower** [comment]
When the pre-processed data matrix is written into the csv file, there is one more column index on the left side of the matrix.The matrix becomes 117 columns...
```
train.to_csv("dataset/VAE_Train+.csv",index=False)
test.to_csv("dataset/VAE_Test+.csv",index=False)
```
